### PR TITLE
Update DocsLayout.js

### LINKED ISSUE #9289: [BUG] Images overflowing on events with json docs
### Description

Navigate to [Events with json docs]( https://www.biodrop.io/docs/how-to-guides/events-json)
Scroll to the right
see that there are images overflowing past the page

Edit: NOTE - this does not happen on mobile, only on desktop/laptop view

Screenshot
bug-events-with-json

### Screenshots

_No response_

### Do you want to work on this issue?

None

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PradeepG-07**
## Fixes Issue
 Fixes Images overflowing on events with json docs #9289
Closes #9289 

## Changes proposed
Adding overflow-auto property 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot 2023-10-04 172525

## Note to reviewers
It will resolve the issue if the problem persists please let me know I have an alternate solution changing lg:w-[100%] to lg:w-[75%] in the docslayout

### CODE REVIEW

**Comment by PradeepG-07** [comment]
Hi @sital002 Could you please review my PR.

**Comment by PradeepG-07** [comment]
Hi @sital002 Could you please merge the pull request, close the issue and assign the hacktoberfest completed label so that it will be counted for my hacktoberfest contribution.
Thank You.

**Comment by sital002** [comment]
> Hi @sital002 Could you please merge the pull request, close the issue and assign the hacktoberfest completed label so that it will be counted for my hacktoberfest contribution. Thank You.

I don't have write access for this repository but don't worry the maintainer will merge your PR and add the label  ```hacktober-accepted```.

**Comment by PradeepG-07** [comment]
Okay 🤝

**Comment by PradeepG-07** [comment]
A humble request to maintainers it's been 2 days since I made a PR if you are free could you please look at it. Because I want to work on other issues as well. Thank you.

**Comment by eddiejaoude** [comment]
@PradeepG-07 you have been asked not to tag people when unrelated as this creates noise, also I have already explained to you here about how the hacktoberfest event labels are not required  https://github.com/EddieHubCommunity/BioDrop/pull/9310#issuecomment-1746331678

**Review by eddiejaoude — APPROVED** [review]
Thank you for the contribution 👍

**Comment by PradeepG-07** [comment]
Sorry for what I have done 😞. I will never repeat it again. Sorry...

**Pull request merged**
