### PR TITLE
Create maithrivh.json

### PR DESCRIPTION
**Pull request by maithrivh**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by sital002 — APPROVED** [review]
Looks good 👍
Welcome to Eddiehub community 🎉🎉

**Comment by maithrivh** [comment]
Thank you @sital002

**Comment by sital002** [comment]
> May i know how to proceed from here on to have a biodrop link? Please can you guide?

The maintainer will merge the PR once they approved it and after that your profile will be visible ```https://biodrop.io/your_username```
you can repoen this and you will get notified once it's merged.

**Comment by eddiejaoude** [comment]
@maithrivh did you mean to close your pull request?

**Comment by eddiejaoude** [comment]
> May i know how to proceed from here on to have a biodrop link?
> Please can you guide?

I will reopen the pull request for you

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍  welcome to BioDrop

**Comment by eddiejaoude** [comment]
Your profile is now live https://www.biodrop.io/maithrivh

**Pull request merged**
