### PR TITLE
fix(docs-testimonial): Update Testimonial Addition Process

### LINKED ISSUE #10055: [DOCS] Update Testimonial Addition Process in Docs
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/docs/how-to-guides/testimonials-json

### Version of BioDrop (for example "v1.2.3")

v2.93.7

### Description

The process outlined for adding a new testimonial to a user using JSON in the documentation is outdated. It directs users to click on the 'Add testimonial' button, which has been removed from BioDrop's latest version. The current method involves navigating to the issues tab, creating a new issue, and selecting the 'Testimonial' template. I believe we should update this information in the docs, along with the screenshots.

### Steps to Reproduce

1. Go to [Testimonials with JSON](https://www.biodrop.io/docs/how-to-guides/testimonials-json) page.
2. Go to the `Giving a Testimonial` section and read the description.

### Screenshots

Procedure highlighted in the docs:

image

How the profile looks now:
image

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Updating the docs to reflect the current procedure for adding a testimonial, along with screenshots for the same, would solve this issue.

### PR DESCRIPTION
**Pull request by ArvindParekh**
## Fixes Issue
Closes #10055 

## Changes proposed
Updated the Testimonial addition process in the docs, now that the `Add Testimonial` button has been removed.
The new process now includes the following steps:
- Go to the Issues Tab
- Create a new Issue
- Select the type `🏆 Testimonial`
- Fill in your testimonial

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before:

image

After:

image

### CODE REVIEW

**Comment by ArvindParekh** [comment]
Also, there's another image that may need updating:

image

This image is based on the fact that an issue with type "testimonial" has been created through the `Add Testimonial` button (and has a pre-populated field of user), which is not the case now. The new issue now will not have any pre-populated field. 
Considering this, do you prefer that I update the image as well? It's a minor change, but we can do it for consistency. Let me know what you think.

**Comment by ThomasCode92** [comment]
As you suggested, I would update the image as well for consistency.
Upon approval of this PR, the documentation for adding testimonials will be accurate and complete.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by eddiejaoude** [comment]
> Also, there's another image that may need updating:
> 
> image
> 
> This image is based on the fact that an issue with type "testimonial" has been created through the `Add Testimonial` button (and has a pre-populated field of user), which is not the case now. The new issue now will not have any pre-populated field. Considering this, do you prefer that I update the image as well? It's a minor change, but we can do it for consistency. Let me know what you think.

this can come in another issue/PR - having the pre-filled image I think it is good, it gives them an example, but the repo name is the previous (old) repo name, so it would be good to update. I will merge this PR so not to block the value it already adds to the users

**Comment by ArvindParekh** [comment]
> > Also, there's another image that may need updating:
> > image
> > This image is based on the fact that an issue with type "testimonial" has been created through the `Add Testimonial` button (and has a pre-populated field of user), which is not the case now. The new issue now will not have any pre-populated field. Considering this, do you prefer that I update the image as well? It's a minor change, but we can do it for consistency. Let me know what you think.
> 
> this can come in another issue/PR - having the pre-filled image I think it is good, it gives them an example, but the repo name is the previous (old) repo name, so it would be good to update. I will merge this PR so not to block the value it already adds to the users

I understand. I can update the image to reflect the new repo name, also pre-populating the name field. 
Should I just directly raise a pr for that and reference this pr, or would you like me to create a new issue?

**Comment by eddiejaoude** [comment]
Please create an issue first

**Pull request merged**
