### PR TITLE
data: akintolarichard

### PR DESCRIPTION
**Pull request by AkintolaRichard**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by sital002 — CHANGES_REQUESTED** [review]
Your filename must match your github username ```data/akintolaRichard.json``` it should be ````data/AkintolaRichard.json```` .Please make the necessary changes to get your profile merged.

**Comment by AkintolaRichard** [comment]
Thank you for the clarification @sital002, I assumed that the name of the should be in lower case.

**Review by SaraJaoude — APPROVED** [review]
I have deleted the duplicate file with the wrong name and can now merge this PR

**Comment by AkintolaRichard** [comment]
Thank you very much @SaraJaoude, I do appreciate.

**Pull request merged**
