### PR TITLE
Nickaldwin patch 1

### PR DESCRIPTION
**Pull request by nickaldwin**
## Fixes Issue
update links and add about section

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
It seems like you've already started using forms for managing your profile, so now you no longer need to update this `json` file. 

You can safely delete this `json` file [here](https://github.com/nickaldwin/LinkFree/delete/nickaldwin-patch-1/data/nickaldwin.json). 

Here are [the docs](https://www.biodrop.io/docs/how-to-guides/editing-forms) that will help you with editing and managing your profile using forms

**Comment by nickaldwin** [comment]
@kumarsonsoff3 i will follow the guide thank you so much

**Comment by kumarsonsoff3** [comment]
I'll close this PR as your latest PR (#10294) is already being merged!

**Comment by nickaldwin** [comment]
@kumarsonsoff3 thank you so much

**Pull request closed without merging**
