### PR TITLE
Changed old twitter icon to X

### LINKED ISSUE #9971: [BUG] Request to update Twitter icon to X on social share
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/krushnarout

### Version of BioDrop (for example "v1.2.3")

v2.97.1

### Description

The twitter icon has been updated to X on footer but it's still same on social share link.

### Steps to Reproduce

Go to https://www.biodrop.io/eddiejaoude and click on social share.

### Screenshots

New issue twitter

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will update the `BsTwitter` to latest X logo from the `react-icons` library.

### PR DESCRIPTION
**Pull request by krushnarout**
## Fixes Issue

Closes #9971 

## Changes proposed

Changed old twitter icon to new X icon.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Sindhuinti — APPROVED** [review]
Looks good to me 🚢

**Review by adityaraute — APPROVED** [review]
For those wondering what's the difference between the two

image

**Review by schmelto — APPROVED** [review]

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Changes seems a bit straight to me, but it gives the following error when we click on the share icon on someone's profile. 

image

**Comment by krushnarout** [comment]
@kumarsonsoff3 I think you forget to add `BsTwitterX` on `import { BsTwitter, BsFacebook, BsLinkedin } from "react-icons/bs";` while checking. Can you double check it?

**Comment by ChinmayMhatre** [comment]
> Changes seems a bit straight to me, but it gives the following error when we click on the share icon on someone's profile.
> 
> image

This might be a separate issue. Can you share which page and which icon. maybe steps to reproduce?

**Comment by kumarsonsoff3** [comment]
> This might be a separate issue. Can you share which page and which icon. maybe steps to reproduce?

I thought the same, but either this icon `BsTwitter` is used in some other module that needs update or something else. 

- I tried undoing these changes, and that works fine. 
- Might want to look at this clip: 
https://www.loom.com/share/f97ea2b6aaac4ea98f67223196ca4f08?sid=bac5b920-f154-45ee-a243-abb9f87a1dc0

**Comment by adityaraute** [comment]
This clip confirms that the PR creates issues that needs to be addressed.
The modal is probably bugging because of the missing icon. thanks for sharing @kumarsonsoff3

**Comment by krushnarout** [comment]
@kumarsonsoff3 @ChinmayMhatre @adityaraute Can anyone tell me, how can I fix this ?

**Comment by adityaraute** [comment]
You have updated your branch and so there is no difference between your fork and this repo at the moment. 
You'll have to once again commit your changes to your branch and then the PR will be mergeable.

**Comment by krushnarout** [comment]
@kumarsonsoff3 I've fixed the error, Please check and let me know any changes needed. 

**Screenshot**

bio

**Review by kumarsonsoff3 — APPROVED** [review]
Looks awesome. Great collaboration everyone. 👍

**Comment by krushnarout** [comment]
Thank you everyone

**Pull request merged**
