### PR TITLE
Create angkul07.json

### PR DESCRIPTION
**Pull request by angkul07**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by kumarsonsoff3 — COMMENTED** [review]
It seems like you're already using forms for managing [your profile](https://www.biodrop.io/angkul07), so there's no meaning of creating a `json` for the same. 

You can continue using forms for managing & editing your profile following these docs: https://www.biodrop.io/docs/how-to-guides/editing-forms

I'll close this PR for the reason mentioned above!

**Comment by angkul07** [comment]
Yeah I know, but @kumarsonsoff3 for some reason, I am unable to add any links to my profile. Whenever I click on add link and fill the form, turn on Enable, it doesn't get update and doesn't show on my profile. I already raise a issue about this in the issue  issue #10062 . That's why I chose to create a `json` file for my profile. Please consider to reopen this pr and approving it and look into the issue. Thank you.

**Comment by kumarsonsoff3** [comment]
Thank you for raising the issue. It should have been fixed now. Please try again and let us know. 

--
>[!Note]
>Just to clearify, that once someone starts managing their profile using forms, their `json` becomes obsolete, which means any content in `json` would then not effect live profile.

**Comment by angkul07** [comment]
It is fixed now. I can now use forms to adding links to my profile.  Thanks :)

**Pull request closed without merging**
