### PR TITLE
data:ianujvarshney.json

### PR DESCRIPTION
**Pull request by ianujvarshney**
**Pull Request: Adding Anuj Varshney's Bio**

**Description:**

This pull request introduces the bio data for Anuj Varshney, providing a comprehensive overview of his skills, current learning focus, and notable milestones. The added information includes details on social media profiles, links, and a milestone related to the "Biodrop" open-source project.

**Changes Made:**

1. Added Anuj Varshney's bio data to the profile directory.
2. Included information on skills, social media profiles, and a significant milestone.
3. Verified that the data adheres to the specified structure and formatting.

**Context:**

The inclusion of Anuj Varshney's bio enhances the profile section by offering a detailed snapshot of his professional journey, skills, and contributions to open source.

**Testing:**

- Manually verified the added data for accuracy.
- Checked the rendering of the bio information in the profile section.

**Dependencies:**

- No dependencies for this pull request.

**Checklist:**

- [ ] The added data aligns with the project's data structure and standards.
- [ ] No breaking changes introduced.
- [ ] The bio information renders correctly in the profile display.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
You already have a profile that you manage via the forms https://www.biodrop.io/ianujvarshney so I will close this PR as it will have no effect on your profile

**Comment by ianujvarshney** [comment]
@eddiejaoude 

# Working with Event Page on Localhost

I am eager to work with the Event page, but I encounter authentication hurdles every time I try to access it. Upon reaching the final authentication step, the sign-in process fails to work, and I'm perplexed about what might be causing this issue.

Upon closer inspection, I discovered that my `username.json` file is missing from the data folder. Realizing this, I added the missing file. that's why added. 

Could you kindly guide me on how to successfully work with the Event page on localhost? I appreciate your assistance in resolving this matter.

**Comment by eddiejaoude** [comment]
You can create your profile using the forms again locally, so the data will be in your local database

**Comment by ianujvarshney** [comment]
> You can create your profile using the forms again locally, so the data will be in your local database

Let me try

**Pull request closed without merging**
