### PR TITLE
Closes #9707 - Keyboard Accesibility Issue with Icon Dropdown Fixed

### LINKED ISSUE #9707: [BUG] Accesibility Issue with Icon Dropdown
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.83.18

### Description

The Icon Dropdown under [AddLink](https://www.biodrop.io/account/manage/link) & [Add Milestone](https://www.biodrop.io/account/manage/link) do not respond to Arrow Key Presses.

### Screenshots

_No response_

### Do you want to work on this issue?

No

### If you want to work on this issue...

_No response_

### PR DESCRIPTION
**Pull request by aryanraj60**
## Fixes Issue

Closes #9707

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/72094124/9b4da1f9-ec43-4169-b73d-a981b1c93b29

### CODE REVIEW

**Comment by SaraJaoude** [comment]
@aryanraj60 I am not sure why you have opened this PR, as the Issue it relates to is still in triage and has not been assigned to you.  

Please familiarise yourself with this project's [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) for any future contributions, to avoid any of your work being wasted and also adding additional work to the maintainers.

On this occasion we will assign the Issue to you and one of the maintainers will review this PR once they reach it in they queue.

**Comment by aryanraj60** [comment]
I'm really sorry for that mam, It will not happen again, I'm new to opensource, I will keep this in my mind next time.

**Comment by adityaraute** [comment]
I went to test this but I realised I can't because I don't have an account haha

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
