### PR TITLE
Fixes #9294 Low contrast color change on the onboarding page.

### LINKED ISSUE #9294: [BUG] Low contrast update on account page
### Description

On this url, there is a section offering hints to complete your profile. [Account onboarding url](https://www.biodrop.io/account/onboarding)

In dark mode, please update the text to be displayed in white (consistent with other dark mode white text)

See screenshot for location of text.

### Screenshots

low-contrast

### Do you want to work on this issue?

None

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sricharanandra**
Closes #9294 
## Fixes Issue
Fixes issue of low contrast text on https://www.biodrop.io/account/onboarding.

## Changes proposed

Used the `dark` class in the element and set to change font color.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Please revert the package.json and package-lock.json file.

**Comment by ChinmayMhatre** [comment]
To revert the package lock and the other file you can follow these steps.

1. go to `main` branch. make sure it is updated by `git fetch upstream` and `git merge upstream/main`  (essentially making sure it is up to date).
2. go back to your `dark-mode-font-change` branch 
3. run this command to revert your file `git checkout -- path to your lock file` and `git checkout -- path to your package json` (please replace the path with the actual path)
4. push the code using `git push origin dark-mode-font-change` that should update this pr

@mohak34  please let me know if anything is not clear. You can use `git checkout main` and `git checkout footer-text-update` to switch between the branches

P.S To avoid this in the future you should use `npm ci` to install the packages instead of `npm install`

**Comment by sricharanandra** [comment]
Alright, I'll send it over.

**Comment by sricharanandra** [comment]
Running into errors in `git chekout -- BioDrop\package.json` (the relative path) and also in the full path. 
For the relative, error message is `error: pathspec 'BioDroppackage.json' did not match any file(s) known to git` and for the full path,  `fatal: Z:Web: 'Z:Web' is outside repository at 'Z:/Web Dev/Hacktoberfest/BioDrop/BioDrop'`.

**Comment by ChinmayMhatre** [comment]
> > Running into errors in `git chekout -- BioDrop\package.json` (the relative path) and also in the full path. 
> > For the relative, error message is `error: pathspec 'BioDroppackage.json' did not match any file(s) known to git` and for the full path,  `fatal: Z:Web: 'Z:Web' is outside repository at 'Z:/Web Dev/Hacktoberfest/BioDrop/BioDrop'`. 
> 
> Please write the paths correctly and check.

Please add a screenshot to the commands you type and the error. 

- you need to make sure main branch is upto date with this repo.
- you need to write the paths correctly.
- also double check command spellings

**Comment by ChinmayMhatre** [comment]
Hey @sricharanandra , I have updated the command there was a slight mistake, my bad. Also you need to use correct file paths. Biodrop/package.json is not the correct path.

I can give you an example
image
Here you can see I am in the `excalidraw` folder in my terminal . and you can see package.json is immediately in the folder so the path would be `./package.json` and similarly for the lock file

**Comment by sricharanandra** [comment]
Nope. Still getting the same error. 
image

**Comment by ChinmayMhatre** [comment]
> Nope. Still getting the same error.
> image

 https://www.youtube.com/watch?v=jHkIXYVpMTo check this video by eddie

**Comment by ChinmayMhatre** [comment]
@sricharanandra how far are we with the suggested changes?

**Comment by ChinmayMhatre** [comment]
> > Tried following the video, didn't seen to work. Will clone the repo again and run `npm ci` this time and redo the changes. Will send it over in a few hours.
> 
> you don't need to clone the repo, you can create a new branch from main and make the changes. But feel free to follow whatever is comfortable to you

**Comment by sricharanandra** [comment]
So the changes in the json files are only in the branch we code in?

**Comment by sricharanandra** [comment]
I should close this PR and make a new one right? For the new branch?

**Comment by ChinmayMhatre** [comment]
> I should close this PR and make a new one right? For the new branch?

Yes you can do that

**Pull request closed without merging**
