### PR TITLE
data:Sxamoecode

### PR DESCRIPTION
**Pull request by Sxamoecode**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Sxamoecode** [comment]
data:Sxamoecode

**Review by kumarsonsoff3 — CHANGES_REQUESTED** [review]
Hey there, 

You're adding an empty file. Please add your data to it. You might want to have a look at quickstart docs: https://www.biodrop.io/docs/quickstart-json

**Comment by Sxamoecode** [comment]
File updated: data:Sxamoecode.json

**Review by accodes21 — COMMENTED** [review]
Looks good

**Review by SaraJaoude — APPROVED** [review]
looks good

**Pull request merged**
