### PR TITLE
fix : Typo mistake in faqs section

### LINKED ISSUE #9374: [DOCS] Typo mistake in faqs section.
### Description

It should be **How much does it cost to use ```BioDrop ?```** instead of **How much does it cost to use**.
Page URL: https://www.biodrop.io/docs/faqs

### Screenshots

image

### Do you want to work on this issue?

Yes

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by VivekYadav193**
Closes #9374 

Updated  "How much does it cost to use" to  "How much does it cost to use BioDrop ?" in "faqs.mdx" file .

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

Before Fixing=>

image

After fixing =>

image

### CODE REVIEW

**Comment by ikunal-04** [comment]
Hey you just worked upon a issue which I listed on and in there I clearly mentioned that I wanted to work on that! Github and open source is about collaboration not competition bro understand this.

**Review by sital002 — COMMENTED** [review]
We are glad that you want to contribute but the issue https://github.com/EddieHubCommunity/BioDrop/issues/9374  isnot labeled ```status: ready for dev```  so can't accept your Pull Request. I would recommend you to read our contributing guidelines and close this Pull Request. 
https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by eddiejaoude** [comment]
> Hey you just worked upon a issue which I listed on and in there I clearly mentioned that I wanted to work on that! Github and open source is about collaboration not competition bro understand this.

Don't worry @ikunal-04 - stealing issues we do not allow on this project. After the issue is triaged the person who requested it first will be given priority

**Comment by eddiejaoude** [comment]
Closing issue as Sital explained it doesn't follow our contributing guidelines

**Pull request closed without merging**
