### PR TITLE
Feat/footer text update

### LINKED ISSUE #9293: [FEATURE] Improvement - footer text update
### Description

In the footer, please update **"Road map"** to **"BioDrop Roadmap"**

This will standardize the language in the footer for both the open source roadmap and biodrop roadmaps to increase consistency and clarity.

### Screenshots

footer

### Do you want to work on this issue?

No

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mohak34**
## Fixes Issue

Closes #9293 

## Changes proposed

Changed in footer.js. The text was changed from Road Map to BioDrop RoadMap

[X] - Footer text update from Road Map to BioDrop Road Map

## Check List 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

image

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
To revert the package lock and the other file you can follow these steps.

1. go to `main` branch. make sure it is updated by `git fetch upstream` and `git merge upstream/main`  (essentially making sure it is up to date).
2. go back to your `footer-text-update` branch 
3. run this command to revert your file `git checkout -- path to your lock file` and `git checkout -- path to your package json` (please replace the path with the actual path)
4. push the code using `git push origin footer-text-update` that should update this pr

@mohak34  please let me know if anything is not clear. You can use `git checkout main` and `git checkout footer-text-update` to switch between the branches

**Comment by ChinmayMhatre** [comment]
> I executed all the commands and i got everything is up to date 

Please check again both files are still present. You need to have the local main branch up to date

**Comment by ChinmayMhatre** [comment]
> To revert the package lock and the other file you can follow these steps.
> 
> 1. go to `main` branch. make sure it is updated by `git fetch upstream` and `git merge upstream/main`  (essentially making sure it is up to date).
> 2. go back to your `footer-text-update` branch 
> 3. run this command to revert your file `git checkout -- path to your lock file` and `git checkout -- path to your package json` (please replace the path with the actual path)
> 4. push the code using `git push origin footer-text-update` that should update this pr
> 
> @mohak34  please let me know if anything is not clear. You can use `git checkout main` and `git checkout footer-text-update` to switch between the branches

@sital002 can you please double check these steps as well

**Comment by ChinmayMhatre** [comment]
> > I executed all the commands and i got everything is up to date 
> 
> Please check again both files are still present. You need to have the local main branch up to date

Try to add screenshots and mention the steps you did. Would help the maintainers to help you

**Comment by ChinmayMhatre** [comment]
Hi @mohak34 , there was a slight mistake in command on 3rd point , my bad. Can you try to do the steps again. if any error do let me know and send the screenshot here. 

The way you can be sure you did it correctly is , the package-lock and package.json will go away from the files changed section above.
image

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution 👍 

Your changes to `components/Footer.js` look good but changes to the `package.json` and `package-lock.json` should not be include in your PR

I made a video on how to avoid this and how to undo these changes https://www.youtube.com/watch?v=jHkIXYVpMTo

**Comment by ChinmayMhatre** [comment]
@mohak34  do you need any help with the changes?

**Comment by SaraJaoude** [comment]
As there has been no activity for over two weeks I am closing this PR.

**Pull request closed without merging**
