### PR TITLE
B satish sutar patch 5

### PR DESCRIPTION
**Pull request by BSatishSutar**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Modified my Bio

### CODE REVIEW

**Review by sital002 — APPROVED** [review]
LGTM!

**Comment by BSatishSutar** [comment]
> LGTM!

Is this merged??

**Comment by sital002** [comment]
> > LGTM!
> 
> Is this merged??

No, the maintainer will merge this PR

**Comment by SaraJaoude** [comment]
@BSatishSutar as explained to you on Discord, given that you are using forms any changes you make to your JSON file will not have any effect. If you want to make changes to your profile please use forms.  

Please delete your JSON file as this is no longer required. 

Screenshot 2023-08-28 at 09 07 26

I will close this PR.

**Comment by BSatishSutar** [comment]
Well, isn't this a fine display of your persistence? You're hell-bent on shoving Forms down my throat, all while conjuring up false claims about my past usage. Bravo! I've finally decided to throw in the towel and surrender to your impressive display of dada-giri (bullying). You win, congratulations. You've successfully worn me down. Enjoy your victory.

**Comment by BSatishSutar** [comment]
I've been thinking about things lately, and it's honestly pretty amusing how you're pushing me to use Forms when I couldn't care less. And that whole BioDrop thing? Yeah, that ship has sailed for me. It's just ridiculous to be coerced by you into doing things I have zero interest in, and then you have the audacity to claim I've used Forms when I haven't even touched it. You really can put on a façade, huh? Just an eye-rolling observation on my part.

Oh, and let's not forget the charming habit you have of hammering on the same false point again and again. Seriously, is that all you've got? Spare me your tiresome rants, won't you? I thought it might be helpful to bring this to your attention.

Now, let's be clear: I might not be losing sleep over this, but I'm all for making my stance crystal clear. I'm not about to waste my time in a place where you clearly undervalue me and where you're trying to puppeteer me into choices. It's a matter of standing up for my beliefs, even if I'm not exactly losing my cool over it.

**Comment by eddiejaoude** [comment]
@BSatishSutar as of the owner of the organisation I feel I need to respond to the abusive comments you have made to one of our maintainers. Clearly this is a very emotional subject for you so I will to you again tell you the facts:

1. As I explained to you on Discord, you have already used forms before the comments above. You can see this in the screenshot of our Discord conversation yesterday. Tech does not lie, you have used the forms to manage your repos, you can see this from the mongo db screenshot below...

Screenshot 2023-08-28 at 11 30 36

2. You mention a persistent push and force to use forms. The only times forms have been mentioned were after you had already used them. Our docs clearly state when you start using forms you can no longer use the json files to manage your profile.

3. Speaking of persistence you keep updating your json file, even if this is merged, it will not reflect on your profile (as previously explained)

Regardless of the facts I have mentioned above, it seems very clear by the way you have written that this community is not a place you want to be in. The last thing we want to do is "force" community members to remain. Feelings such as yours do not make it a safe environment for the other community members.

Not only are the facts you have written incorrect but also the way you have written them is unacceptable. This breaks our Code of Conduct and I will be banning you from the community.

**Pull request closed without merging**
