### PR TITLE
Fix avatar size testimonials

### LINKED ISSUE #8947: [BUG] Inconsistent Profile Image Sizes on manage testimonials
### Description

As show in the screenshot, the profile images are not consistent on the manage testimonials page

The solution is to make them consistent. 

### Screenshots

image

### Do you want to work on this issue?

Yes

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by allexgut**
## Fixes Issue 

fixes #8947

## Changes proposed

Wrapped the profile picture element in a flex div.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

## Note to reviewers
The testimonials in the account page currently look off from a spacing perspective. I would suggest to also adjust it by using the public testimonials as an example since it looks way better. I think it's best to open another issue for that as it is a bit more broad in scope than the current one.

### CODE REVIEW

**Review by sital002 — COMMENTED** [review]
We are glad that you want to contribute but you cannot send Pull Request without getting the issue assigned to you. The issue #8947 isnot assigned to you, so we can't accept your Pull Request. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md.
Please don't start working on the issue before getting assigned. You can close this Pull Request.

**Comment by allexgut** [comment]
I understand, sorry, I was looking at another repository that didn't require issues to be assigned before starting work and got confused. I'll comment now.

**Comment by allexgut** [comment]
Closing this PR for now. I'll open a new one as soon as I get the issue assigned to me.

**Comment by SaraJaoude** [comment]
@allexgut please feel free to re-open as I have assigned this to you.

As to the comments on the `Note to Reviewers` and your new idea, please do open a new issue.  If you wish for that to be assigned to you there is a section in the issue description which allows for this.  Please do take a look at the Contributing Guide  sent to you above as this explains the triage process for issues on this project, as well as the fact that we only assign one issue per contributor at any one time.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
