### PR TITLE
fix: Milestone Icon Overflow by Removing Rounded Styling

### LINKED ISSUE #9824: [BUG] Some icons in milestones overflow
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

biodrop.io

### Version of BioDrop (for example "v1.2.3")

2.90.0

### Description

Some icons used in my milestone overflow out of the container.

Here are the icons 
image
FaCodeBranch

image
FaDev

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to https://www.biodrop.io/account/manage/milestones page.
1. Use one of the above icons in a milestone to test the bug

### Screenshots

_No response_

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by Kamaruddheen**
## Fixes Issue

Closes #9824

## Changes proposed

- Removed `rounded-full` class from DisplayIcon component
- Confirmed overflow no longer occurs with **FaCodeBranch** and **FaDev** icons as well as other milestone icons I tested.
- Tested on accounts milestones page

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

| Light | Dark | 
|---|---|
| image  | image |

### CODE REVIEW

**Review by amitabh-sahu — APPROVED** [review]

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by Kamaruddheen** [comment]
Looks like test case 2 still getting timeout exception on all 4 attempts ☹️

**Comment by eddiejaoude** [comment]
> Looks like test case 2 still getting timeout exception on all 4 attempts ☹️

this is not because of your PR, this is a general issue that has come up recently - I am looking to fix it, then we can update your PR and get it merged. Let's see how it goes 🤞 https://github.com/EddieHubCommunity/BioDrop/pull/9882

**Comment by Kamaruddheen** [comment]
> > Looks like test case 2 still getting timeout exception on all 4 attempts ☹️
> 
> this is not because of your PR, this is a general issue that has come up recently - I am looking to fix it, then we can update your PR and get it merged. Let's see how it goes 🤞 https://github.com/EddieHubCommunity/BioDrop/pull/9882

Thanks, got little worried 😅

**Comment by eddiejaoude** [comment]
> Thanks, got little worried 😅

Sorry for the confusion. All working now 🎉

**Pull request merged**
