### PR TITLE
Create Haruhue.json

### PR DESCRIPTION
**Pull request by Haru-hue**
## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Haru-hue** [comment]
@eddiejaoude @Pradumnasaraf

**Comment by eddiejaoude** [comment]
Please do not tag maintainers like that, we already get the notification, adding more notifications does not help. It was only a few minutes since you raised the PR, we all live in different timezones, please be patient, we will get to your PR soon.

Please read the contributing guide https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by Haru-hue** [comment]
> Please do not tag maintainers like that, we already get the notification, adding more notifications does not help. It was only a few minutes since you raised the PR, we all live in different timezones, please be patient, we will get to your PR soon.
> 
> Please read the contributing guide https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

Sorry about that

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
Please remove the changes to the file `TobySolutions/testimonials` - this does not relate to your Profile or a testimonial given by you or to you.

**Comment by Haru-hue** [comment]
> Please remove the changes to the file `TobySolutions/testimonials` - this does not relate to your Profile or a testimonial given by you or to you.

I already did that

**Comment by eddiejaoude** [comment]
> I already did that

You deleted the file from someone else's profile, for your PR to be accepted please remove your changes to the file (not delete the file) from your Pull Request, there should be no changes over than your json file in the "files changed" tab, please check again

Here is a screenshot to help

Screenshot 2024-01-23 at 09 59 28

**Comment by Haru-hue** [comment]
Tried undoing it but it was not working and frustrating, I made a new one:
https://github.com/EddieHubCommunity/BioDrop/pull/10171

**Pull request closed without merging**
