### PR TITLE
Increase execution time for loading json files

### LINKED ISSUE #9135: [FEATURE] Increase execution time for loading json files
### Description

> The default timeout will be reduced to 15 seconds. Beginning Oct 1, a function will be stopped if it executes for more than 15 seconds. This change helps prevent uncontrolled function usage due to abuse and reduces the risk of unexpectedly high bills.

In config file `vercel.json` add
```js
{
  "functions": {
    "api/system/reload.js": {
      "memory": 3008,
      "maxDuration": 60
    }
  }
}
```

https://vercel.com/docs/functions/serverless-functions/runtimes?mkt_tok=MDAxLUxSRy0xOTQAAAGOV4bcIFqHBzkDjbbbS_WZ47UCs0j2Za5MqQ0XC0L23NJyXVoLB4Rcp5wHsYRD_Rkzt8DuMwK8FsLedhwp40AThPgwKpv_mLiCUZS7vZlJ#maxduration

### Screenshots

_No response_

### Do you want to work on this issue?

None

### Additional information

**note**: must be completed and merged by the 1st of October

### PR DESCRIPTION
**Pull request by rizahmeds**
## Fixes Issue
Fixes #9135 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution 👍  but your pull request contains extra changes not required for this pull request

**Comment by rizahmeds** [comment]
> Thank you for your contribution 👍 but your pull request contains extra changes not required for this pull request

Created another PR [https://github.com/EddieHubCommunity/BioDrop/pull/9142](https://github.com/EddieHubCommunity/BioDrop/pull/9142), as the previous one had conflicts.

**Comment by eddiejaoude** [comment]
To avoid conflicts with yourself, always use a new branch from main https://www.youtube.com/watch?v=FnxFwyzm4Z4

**Comment by rizahmeds** [comment]
Thanks for the suggestion @eddiejaoude

**Pull request closed without merging**
