### PR TITLE
Update UserRepos.js

### LINKED ISSUE #9297: [FEATURE] Open Issue count badge on repo page
### Description

This issue is to add a new badge on the repo pages to show if a repo has any open issues. This will help contributors discover new repositories to contribute to.

https://www.biodrop.io/repos

### Screenshots

Screenshot of location of new badge.  Color and icon can be chosen by the developer - can discuss if needed

new-badge-location

### Do you want to work on this issue?

No

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PradeepG-07**
## Changes proposed
Added a new badge on the repo pages to show if a repo has any open issues.
Closes #9297

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good, thank you 👍 

note: next time please add a screenshot to the pull request description

**Comment by PradeepG-07** [comment]
Hi @eddiejaoude could you please add the hacktoberfest-accepted label for it so that my merged request could be counted as hacktoberfest contribution

**Comment by eddiejaoude** [comment]
> Hi @eddiejaoude could you please add the hacktoberfest-accepted label for it so that my merged request could be counted as hacktoberfest contribution

It will be accepted because we have the `hacktoberfest` topic on the repo... (it is `topic` or `label`)

Screenshot 2023-10-04 at 08 51 34

```
[PARTICIPATING] YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR HAVE THE “HACKTOBERFEST-ACCEPTED” LABEL.
```

Screenshot 2023-10-04 at 08 50 26

You can read more about the hacktoberfest rules on the official website
https://hacktoberfest.com/participation/

**Comment by PradeepG-07** [comment]
Many thanks for the reply 🤝

**Pull request merged**
