### PR TITLE
updated css file

### PR DESCRIPTION
**Pull request by anirudh-hegde**
Added other font-family names to the file.

### CODE REVIEW

**Comment by anirudh-hegde** [comment]
Also I added another Node.js image version to the Dockefile to ensure that application consumes less memory space.

**Comment by Dun-sin** [comment]
@anirudh-hegde this doesn't seem to be solving an issue, you should read the project's [contributing guidelines](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) so you can work on related things in the future and not waste your time.

**Comment by Dun-sin** [comment]
> Ya, will try to contribute to this project that will make a huge impact

doesn't need to be huge, just need to be right

**Comment by amandamartin-dev** [comment]
Hello @anirudh-hegde while your enthusiasm is appreciated, please refer to the contributing guide @Dun-sin linked.  Will close this PR as there is no open issue it is related to.

**Pull request closed without merging**
