### PR TITLE
fix: Re-ordering tags with Drag-and-Drop

### LINKED ISSUE #9768: [FEATURE] Re-ordering tags with Drag-and-Drop
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I was updating my profile by adding some tags. I added all the tags. I just felt like re-ordering all the programming languages and organize them together. I went ahead to drag and re-order the tags but discovered the feature hasn't been implemented yet🙄.

 We can enhance user experience by implementing a drag-and-drop feature that will allow users to organize tags in an order that makes sense to them, aligning with their preferences or the way they prioritize certain skills or interests without having to delete ones that they have already entered.

ReorderingTag

### Proposed Solution

A solution similar to the following video that I am recorded from Upwork would be great as far as implementation is considered

https://github.com/EddieHubCommunity/BioDrop/assets/72060440/14c6ab56-a6ed-4c5f-8285-b68a5949d71a

### Screenshots

_No response_

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by Abhishek-90**
Closes #9768 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/43419831/2483e871-c0d5-46b5-8ca1-0ee16dd1b710

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
Other can add their suggestions. One this I see is that the tags don't seem to be draggable, unless someone accidentally find it. We need to update the cursor while the tag is being hovered.

**Comment by Abhishek-90** [comment]
@ChinmayMhatre Maybe changing cursor on hover is a good idea, will make the change and push it.

**Comment by Abhishek-90** [comment]
@ChinmayMhatre I have added the onHover effect on list items. 


https://github.com/EddieHubCommunity/BioDrop/assets/43419831/473ff5ff-2011-49b0-85ee-79389a267a70

**Comment by sital002** [comment]
Please resolve the merge conflicts

**Comment by Abhishek-90** [comment]
> Please resolve the merge conflicts

@sital002 Merge conflicts resolved. I have also raised a few concerns on the issue for this pull request.

**Comment by eddiejaoude** [comment]
Looks good 👍

**Pull request merged**
