### PR TITLE
fix: disable pwa due to caching errors

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
In case you haven't seen it, there's some info about manually setting caching for getSSP in the next docs. Not sure if it applies in this case, was just curious and reading 

https://nextjs.org/docs/pages/building-your-application/deploying/production-checklist

**Comment by amandamartin-dev** [comment]
Also it appears there are a number of similar issues in the next pwa repo. I won't link all the responses here as Imy sure you'll find them easily, but this def seems like something folks have figured out how to solve which is promising

**Comment by eddiejaoude** [comment]
> Also it appears there are a number of similar issues in the next pwa repo. I won't link all the responses here as Imy sure you'll find them easily, but this def seems like something folks have figured out how to solve which is promising

Thanks @amandamartin-dev , yes please link those here 👍

**Comment by eddiejaoude** [comment]
I think I deployed a fix now 🤞  https://github.com/EddieHubCommunity/BioDrop/pull/9784

**Pull request merged**
