### PR TITLE
Premium Stripe integration

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

TODO
- [x] Premium feature: hide navbar/footer
- [x] Deploy to preview
- [x] Lock down Stripe webhook
- [ ] Premium feature: Link detailed stats page
- [x] Premium feature: Profile referrer pie graph + top referrers (data https://github.com/EddieHubCommunity/LinkFree/pull/8654)
- [x] Light/Dark mode check for new pages
- [ ] Deploy to production
   - [x] Set environment variables for production
   - [x] Stripe webhook url
- Admin
   - [ ] List Premium users
- Pricing page
   - [x] premium plan to have badge `30 days free`
   - [x] feature description
- Tests
   - [x] free user
   - [x] premium user

IDEAS
- [x] data: referrer
- [x] location stats

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8647"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Repo feature for home page

Screenshot 2023-08-15 at 14 20 23

**Comment by hellofaizan** [comment]
> Repo feature for home page
> 
> Screenshot 2023-08-15 at 14 20 23
> 

My project got listed at last number in this image 😀

**Comment by Pradumnasaraf** [comment]
Hey,

**Comment by Pradumnasaraf** [comment]
are

**Comment by Pradumnasaraf** [comment]
Apologies, for closing. I clicked on the wrong Keyboard shortcuts.

Here are a couple of feedbacks after using testing it.

**1) Getting a 500 when I click on the Account button.**
**2) When I entered my email, it gives me an error. Now it says**
Screenshot 2023-08-19 at 1 21 06 PM

**3) When I clicked on continue (from above), it sent me an email to do the payment and manage. Now, I am done with everything (adding the card and done with the payment), the continue button is not working.** 
Screenshot 2023-08-19 at 1 24 23 PM

**Comment by schmelto** [comment]
Dark mode is not supported on Pricing page:
image

**Comment by schmelto** [comment]
Learn more about Premium should redirect to the pricing page not searching for user

image

**Comment by eddiejaoude** [comment]
Thank you for testing and the feedback ❤️

**Comment by schmelto** [comment]
Pricing page in dark mode is looking good to me:
image

**Comment by eddiejaoude** [comment]
Thanks @schmelto for re-testing 👍

**Comment by eddiejaoude** [comment]
Untitled-8

**Comment by schmelto** [comment]
Location stats are bug for dark mode: 
image

**Comment by eddiejaoude** [comment]
Thank you @schmelto ❤️

**Pull request merged**
