### PR TITLE
data: fix testimonials that i broke because i had changed my username…

### PR DESCRIPTION
**Pull request by xkrishguptaa**
Okay I got some explanation to do, probably, which I'm not going to do, but here is the fix

it renames my second last username on link free to my current ones which I inconveniently forgot to update the last time in the pr

fixed it @loftwah

### CODE REVIEW

**Comment by loftwah** [comment]
image

Cheers Krish 🎉🎉

**Comment by xkrishguptaa** [comment]
no bullying lmao dean

**Review by kumarsonsoff3 — COMMENTED** [review]
Thanks for renaming these all, Krish! 👍 

Could you please justify why the files related to `web3community.json` are being deleted!?

**Comment by xkrishguptaa** [comment]
web3community.json is being deleted because I made it back when the org was web3community now it is WebXDAO, I am not renaming it because organization profiles are not available in BioDrop rn, so I though removing might be the best idea.

**Review by kumarsonsoff3 — APPROVED** [review]
Okay, Thanks! LGTM 👍

**Pull request merged**
