### PR TITLE
[FEATURE] Edit button on manage links page

### LINKED ISSUE #8824: [FEATURE] Edit button on manage links page looks out of place
### Description

On the links page, we have the edit button over the button itself, and it's covering the icon such that it looks a little bit weird. Is there no way to shift the edit circle? Maybe put it at the end of the link button, or within it like the milestone page?

### Screenshots

Screenshot (182)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by harshu0026**
Closes #8824 

Fixes Issue #8824 

Changes proposed

Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

Screenshots

Screenshot 2023-09-08 200700

Screenshot 2023-09-08 200559

### CODE REVIEW

**Review by sital002 — COMMENTED** [review]
We are glad that you want to contribute but you cannot send Pull Request without getting the issue assigned to you since  this issue is assigned to someone else, we can't accept your Pull Request. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md.
Please close this Pull Request.

**Comment by harshu0026** [comment]
Sure no worries

**Comment by eddiejaoude** [comment]
Thanks @harshu0026 and @sital002 is correct 👍 but please comment on the issue as I don't think there has been any activity for 2 weeks on that issue, and from our contributing guide it can be re-assigned after 2 weeks with no activity - comment and the maintainers can take a look into the status https://github.com/EddieHubCommunity/BioDrop/issues/8824

**Comment by harshu0026** [comment]
Sure I do

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing. The button overlaps other features that you might not have setup in your local dev environment 

Screenshot 2023-10-25 at 21 47 57

**Comment by eddiejaoude** [comment]
No activity for over 2 weeks, I will close and unassign so it is not blocked

**Pull request closed without merging**
