### PR TITLE
feat: create Label component

### LINKED ISSUE #8840: [BUG] <Irregular margins on the account profile tab form>
### Description

The margin space between the labels and inputs are not regular on the profile tab

### Screenshots

profile issue

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hankadev**
## Fixes Issue #8840 

fixes #8840 

## Changes proposed
Created a reusable `Label` component and replaced all `label` html tags with it. This way the styling is defined only once. 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Before:
image

After:
image

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍

**Comment by eddiejaoude** [comment]
Screenshot 2023-09-05 at 05 47 14

**Comment by eddiejaoude** [comment]
Oops put the image in the wrong PR sorry 🤦‍♂️

**Comment by hankadev** [comment]
> Looks great 👍

Thanks :blush:

**Pull request merged**
