### PR TITLE
modified my profile by adding the freelancing link

### PR DESCRIPTION
**Pull request by ibilalkayy**
## Changes proposed

I modified my profile by adding the freelancing link

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thanks Bilal, but as mentioned in your previous PR, you are using forms on BioDrop, your json file will now be ignored by the app and you must continue to use forms. You can see the failing GitHub Action also confirming this, so I will close your PR, please continue to update your profile using the BioDrop forms you have started using already.

https://github.com/EddieHubCommunity/BioDrop/actions/runs/7696290649/job/20970881765?pr=10194

Screenshot 2024-01-29 at 14 29 00

**Comment by ibilalkayy** [comment]
@eddiejaoude where are the forms?

**Comment by ibilalkayy** [comment]
Okay I will use the forms. I thought that I can use both forms and Pull request

**Comment by eddiejaoude** [comment]
There will be an alert above the forms stating your json will be ignore rom now on. Here are the docs about forms https://www.biodrop.io/docs/how-to-guides/editing-forms

**Pull request closed without merging**
