### PR TITLE
Manage Testimonial Profile image

### LINKED ISSUE #7846: [FEAT] profile icon does not appear
### Description

I was exploring the new version of my Linkfree profile and noticed that the profile pic of the person who gave me a testimonial is no longer there.

EDIT: when managing testimonials the profile picture of the author is not shown as it is on the public profile

### Screenshots

Profile pic does not appear in testimonial section

### Additional information

I’m open to collaborating with someone on this issue ~~once I solve #7844~~ (this is misleading as it appears that this issue is dependent on the other issue, which it is not).

### PR DESCRIPTION
**Pull request by DaduDev**
## Fixes Issue

Edit: Fixes #7846

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8432"></a>

### CODE REVIEW

**Comment by eddiejaoude** [comment]
What issue is this for, please use the template and link to the relevant issue

**Comment by DaduDev** [comment]
For some reason, I can't use the code on my local device and I'm working on the following issue:
https://github.com/EddieHubCommunity/LinkFree/issues/7846

**Review by azhechkova — APPROVED** [review]

**Comment by ChinmayMhatre** [comment]
@DaduDev can you provide sceenshots like Eddie suggested

**Comment by SaraJaoude** [comment]
As there has been no activity for two weeks I am closing this PR>

**Pull request closed without merging**
