### PR TITLE
fix: secondary navbar overflow (#9891)

### PR DESCRIPTION
**Pull request by ankittankal**
## Fixes Issue

closes [#9891 ](https://github.com/EddieHubCommunity/BioDrop/issues/9891)

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

[Screenshot_20231225_155413](https://github.com/EddieHubCommunity/BioDrop/assets/68264331/00f6b4bf-81e8-41b8-85d0-68bedd55afb0)

## Note to reviewers
I corrected the issue by setting a custom 900px breakpoint specifically for tablets, as the mobile view is intended for smaller screens and not for large screens(1024px).

### CODE REVIEW

**Comment by ankittankal** [comment]
Could anyone provide a review on my pull request, please?

**Comment by eddiejaoude** [comment]
Sorry for the delay, reviewing it now

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution 

I don't think we should introduce a new screen size because of the content, we should adjust the content.

my thoughts for small screens
- main navigation: hide theme toggle, GitHub icon and profile picture
- tabs: switch to drop down nav sooner

**Comment by eddiejaoude** [comment]
@ankittankal why did you request a review, I gave one a few hours ago and there are no new changes or comments?

**Comment by ankittankal** [comment]
> @ankittankal why did you request a review, I gave a review and feedback a few hours ago and there are no new changes or comments?

I appreciate your initial review and feedback. Apologies for the accidental re-review request; it was unintentional. I'll ensure to avoid any confusion in the future.

**Comment by ankittankal** [comment]
hey Eddie, first point is already what happens, git, theme and profile icon are hide in smaller screen.

and the second point is what I have done in new changes, I introduced a screen because the next breakpoint after sm is md  which would be too soon to start hiding icons.

**Comment by eddiejaoude** [comment]
>  I introduced a screen because the next breakpoint after sm is md which would be too soon to start hiding icons.

I am keen to keep things simple and this will have a knock on effect for other pages. To keep things simple for now I think we should stick to the original break points and make other decisions accordingly - I don't see hiding things earlier as a problem if there is no space

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
