### PR TITLE
Create AbisolaMajeed

### PR DESCRIPTION
**Pull request by AbisolaMajeed**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by sital002 — CHANGES_REQUESTED** [review]
Your filename must have .json at the end  instead of ```data/AbisolaMajeed``` it should be ```data/AbisolaMajeed.json```
Please make the necessary changes to get your profile merged.

**Comment by AbisolaMajeed** [comment]
> Your filename must have .json at the end instead of `data/AbisolaMajeed` it should be `data/AbisolaMajeed.json` Please make the necessary changes to get your profile merged.

I just renamed the file. Kindly review the change.

**Review by kumarsonsoff3 — COMMENTED** [review]
It seems like you've already been using the forms for managing your profile [here](https://www.biodrop.io/AbisolaMajeed), so there is no point in creating a `json` for the same. 

You can keep managing your profile using forms and might want to look at these docs: https://www.biodrop.io/docs/how-to-guides/editing-forms which will help you edit your profile using forms!

I'll close this PR for the reason mentioned above. Please feel free to reach out if you've any questions :)

**Comment by AbisolaMajeed** [comment]
> It seems like you've already been using the forms for managing your profile [here](https://www.biodrop.io/AbisolaMajeed), so there is no point in creating a `json` for the same.
> 
> You can keep managing your profile using forms and might want to look at these docs: https://www.biodrop.io/docs/how-to-guides/editing-forms which will help you edit your profile using forms!
> 
> I'll close this PR for the reason mentioned above. Please feel free to reach out if you've any questions :)

I’m not sure of how to make a PR when I update my profile with the form. I need the PR to reflect with respect to Tublian

**Comment by eddiejaoude** [comment]
Once you start using forms to manage your profile, you need to continue using forms to update your profile

**Pull request closed without merging**
