### PR TITLE
fix: testimonials for profiles with forms

### LINKED ISSUE #8794: [BUG] Testimonials not showing up
### Description

I've gotten two testimonials so far and they aren't showing up on my profile

### Screenshots

Screenshot_2023-08-26-14-10-02-749_com github android-edit

Screenshot_2023-08-26-14-10-58-854_io github forkmaintainers iceraven-edit

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixes #8794

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by amandamartin-dev** [comment]
Looking at this, but unsure how to test as adding a new testimonial creates a github issue so I don't believe I can complete the flow in the test env.  I also tested searching for the user that opened the issue while running in gitpod, but the data is not synced with prod.  

Working in gitpod, please advise if I am missing something obvious

**Comment by eddiejaoude** [comment]
Sorry I should have written some instructions on how to test it

- manage profile via forms
- add a json testimonial manually or delete an existing testimonial from your profile in the database 
- hit new api end point `/api/system/testimonials-forms?secret=development`
- and the testimonial should be (re)added

**Comment by amandamartin-dev** [comment]
> Sorry I should have written some instructions on how to test it
> 
> * manage profile via forms
> * add a json testimonial manually or delete an existing testimonial from your profile in the database
> * hit new api end point `/api/system/testimonials-forms?secret=development`
> * and the testimonial should be (re)added

Okay looking at this again - I see no option to add testimonials via forms (on prod or in gitpod)
I have no testimonials right now, this could be why? 

Will add one manually via the json to test, but will not be able to test the forms flow if that needs testing as well

**Comment by amandamartin-dev** [comment]
Okay, currently testing is unsuccessful - unclear if it is me or the code.

Steps completed (in Gitpod)

Add a new testimonials folder and json to my own profile folder
hit the API endpoint
the page never reloads /api/system/testimonials-forms?secret=development
In the terminal, this message is seen "API resolved without sending a response for /api/system/testimonials-forms?secret=development, this may result in stalled requests."

Let me know how to test further or if this indicates some other issue that needs fixing first, not sure what's up on my end.

**Comment by eddiejaoude** [comment]
Oh strange. Is this a new Gitpod environment or an existing one? If new you will need to visit `/api/system/reload?secret=development` first, to load the profiles (sorry I should have mentioned that, I assumed it would be an existing dev environment 🤦‍♂️ ). Then create or update your profile with the forms and add a json testimonial to your folder (or delete an existing testimonial from your profile in the database)

Can you check you have the latest code in the branch also

**Comment by amandamartin-dev** [comment]
Test 2

Steps (in gitpod)
Open Gitpod
Switch to fix-testimonials-forms branch
add env variables for my oauth
hit data api to load profiles
log in
go to testimonials in profile - see there are none and no options to add via forms
create a testimonials folder in my profile
copy an existing testimonial into my folder/save
hit testimonials API endpoint
nothing happens

Video (too big to attach, I'll see if I can send in Discord)

**Comment by eddiejaoude** [comment]
Thanks for testing again Amanda! I tested it your way also, not just deleting a testimonial and seeing it re-appear but also moving someone else's to my folder - both created a new entry in my profile

Can you share the output from your terminal, mine looks like this...

```js
The server environment variables are valid!
[17:39:28.117] INFO (9047): DB connection successful:
[17:39:28.140] INFO (9047): updating testimonial FrancescoXX for profile eddiejaoude
[17:40:02.121] INFO (9047): updating testimonial Dun-sin for profile eddiejaoude
```

**Review by amandamartin-dev — APPROVED** [review]
Everything is working as expected.  My user was not on forms in the test env.  Thanks for the help debugging my test end.

**Pull request merged**
