### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by dan-mba**
## Changes proposed
Update non-major version dependencies
Update Next to 14
Update engine to >=18.17 (New Next minimum node version)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Hi @dan-mba is this ready, can we take it out of draft?

**Comment by dan-mba** [comment]
I wanted to wait a few days to make sure that Next 14 didn't get a quick point release due to a regression.

I also noticed an update to storybook that came out today mentioning improvements for Next 14. I will get that added & if there is no update to Next by tomorrow, I will mark it ready for review.

**Comment by eddiejaoude** [comment]
Sounds like a good plan 👍  no rush, was just checking in

**Review by eddiejaoude — APPROVED** [review]
Great, thank you 👍

**Pull request merged**
