### PR TITLE
feat: sharing our content in standup

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

With all the Twitter "fun" going on (while I couldn't sleep) I thought it would be interesting to create a MVP mini twitter but with Markdown

TODO
- [ ] report button
- [ ] admin page of reported items
- [ ] admin can delete items that are reported and offensive

Screenshot 2023-07-02 at 05 21 39

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7915"></a>

### CODE REVIEW

**Comment by CBID2** [comment]
Love this!

**Comment by CBID2** [comment]
Now that think about it, I think there should be some sort of liking system" but can shuffle for engagement purposes.

**Comment by CBID2** [comment]
Now that I think about it @eddiejaoude, a liking system wouldn't be too bad. It would create engagement. There just has to be away to make sure folks feel like they had a chance to shine. 🤔

**Comment by eddiejaoude** [comment]
I think these features can come in a future PR. Let's see if this feature even gets used, or maybe it will be spammed so we might have to add restrictions or even remove it like we had to with the Discover page 😢

**Comment by eddiejaoude** [comment]
Closing my PR as not planning to include in the project just yet

**Pull request closed without merging**
