### PR TITLE
feat: add tabs to url (Fix pr 9007)

### LINKED ISSUE #8969: [FEATURE] Profile show tab using query parameter
### Description

It would be great to be able to share our profile with a query parameter so that it can display the tab directly - for example I was chatting to someone about the events I am attending

- query parameter for tab
- click tab also sets the parameter 
- tab displays if query parameter set 

### Screenshots

_No response_

### Do you want to work on this issue?

None

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

Fix PR https://github.com/EddieHubCommunity/BioDrop/pull/9007

closes #8969

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Dun-sin — APPROVED** [review]
Looks way better than mine

**Comment by eddiejaoude** [comment]
> Looks way better than mine

Thank you, but no it doesn't, just a different way of doing it - plus you did all the hard work. It still is not perfect, we might need to use React `memo` to prevent a re-render each time on the tabs, but that can come in another PR (I think)

**Review by badrivlog — APPROVED** [review]
Nice work💪

**Comment by eddiejaoude** [comment]
I also just added automated tests to check the tab switching and also the deep nesting directly to the tab.

**Pull request merged**
