### PR TITLE
Updated my account details PoulavBhowmick.json

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@sital002 Please merge this

**Review by sital002 — APPROVED** [review]
Looks great 👍

**Review by sital002 — CHANGES_REQUESTED** [review]
Looks like I missed one thing  you have changed the filename please change it so that it matches your GitHub username instead of ```data/PoulavBhowmick.json``` it should be ```data/PoulavBhowmick03.json```.
Please make the necessary changes to get the profile merged.

**Comment by eddiejaoude** [comment]
> sital002 Please merge this

@PoulavBhowmick03 please read our [contributing guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md), here are a few notes...
1. it is not good practice to tag people, the maintainers got the notification of your pull request and are working through them adding extra notifications does not help
2. why "merge"? it should be "review"

**Comment by PoulavBhowmick03** [comment]
I have made the changes

**Review by sital002 — APPROVED** [review]
Looks good 👍

**Pull request merged**
