### PR TITLE
FIX : [BUG] groups field dropdown shift layout while suggestions are shown #10163

### PR DESCRIPTION
**Pull request by tix980**
Closes [#10163](https://github.com/EddieHubCommunity/BioDrop/issues/10163)

## Fixes Issue

Closes [#10163](https://github.com/EddieHubCommunity/BioDrop/issues/10163)

## Changes proposed
Just implementing the solution that we used for icon suggestion drop down here is the link for the https://github.com/EddieHubCommunity/BioDrop/pull/9898

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Laptop
laptop

### Mobile
mobile

### CODE REVIEW

**Comment by sital002** [comment]
Sorry for the late reply 
The dropdown isn't clearly visible in the light mode.
There is already a PR for this problem here is the link for it https://github.com/EddieHubCommunity/BioDrop/pull/10232
image

**Comment by tix980** [comment]
No worries :)! Thank you for the feedback and the link. I will get the light mode issue fixed.

**Comment by tix980** [comment]
Hello sital002, I have fixed the group dropdown isn't clearly visible in the light mode issue. Here is the screenshot:
white-mode-fix

**Review by sital002 — APPROVED** [review]
Looks good 👍 Thanks for the contribution

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Thanks for Contributing! 🎉

**Pull request merged**
