### PR TITLE
Fix: [Feature]:On Mobile hide: stats, Add Testimonial button and tags

### PR DESCRIPTION
**Pull request by AbhishekBhure**
## Changes proposed

1. Added hidden class and replaced flex class with md: flex in Tag.js file.
2. Added hidden class and replaced flex class with md: flex in [username.js] file.
3. Added hidden and md: block classes in the BasicCard.js file.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

fix

## Note to reviewers
Please consider only the e2d4b67 commit all other commits do not change any code

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution. I think you have changes here that are not part of your pull request

**Comment by AbhishekBhure** [comment]
> Thank you for the contribution. I think you have changes here that are not part of your pull request

Yes, I can see some changes in the Input.js file, can I remove that file by deleting it?

**Comment by eddiejaoude** [comment]
> Yes, I can see some changes in the Input.js file, can I remove that file by deleting it?

no, because this would still be a change to the file. 

I made a video on how to revert the file https://youtu.be/jHkIXYVpMTo?si=iYZtQRItl9ClgUhb&t=268

**Comment by AbhishekBhure** [comment]
> > Yes, I can see some changes in the Input.js file, can I remove that file by deleting it?
> 
> no, because this would still be a change to the file.
> 
> I made a video on how to revert the file https://youtu.be/jHkIXYVpMTo?si=iYZtQRItl9ClgUhb&t=268

Ok,  so I need to revert back Input.js file?

**Comment by eddiejaoude** [comment]
> Ok, so I need to revert back Input.js file right?

Remove any changes you don't want in your pull request

**Review by sital002 — COMMENTED** [review]
Thank you for the contribution but some tests are failing.

**Comment by AbhishekBhure** [comment]
> Thank you for the contribution but some tests are failing.

Yes, I am working on it

**Comment by AbhishekBhure** [comment]
Took same pull request twice, so I am closing this pull request

**Pull request closed without merging**
