### PR TITLE
No Space between add link and first link #9406 Fixed

### PR DESCRIPTION
**Pull request by donishyar**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

> before and after the changes

img1

> changes check with all pages that uses the layout and encounter with no issue.

img3

## Note to reviewers

please accept my pr if it was fair.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Original PR https://github.com/EddieHubCommunity/BioDrop/pull/9822

**Comment by donishyar** [comment]
Has my pr been accepted?

**Comment by eddiejaoude** [comment]
The component `Page` is used in 44 files, these will all need to be tested

**Comment by donishyar** [comment]
> [eddiejaoude](https://github.com/eddiejaoude)



> The component `Page` is used in 44 files, these will all need to be tested


should i test it or someone else does ?

**Comment by eddiejaoude** [comment]
> > [eddiejaoude](https://github.com/eddiejaoude)
> 
> > The component `Page` is used in 44 files, these will all need to be tested
> 
> should i test it or someone else does ?

You need to test your own changes, otherwise how do you know they work correctly and don't have a negative effect on the project?

**Comment by donishyar** [comment]
I test all 44 files , it does have any negative effect on the project.

**Comment by eddiejaoude** [comment]
I have tested it and it makes the spacing on every page bigger

BEFORE: profile page

Screenshot 2023-12-18 at 07 00 43

AFTER: profile page

Screenshot 2023-12-18 at 07 00 48

BEFORE: search

Screenshot 2023-12-18 at 07 01 25



AFTER: search

Screenshot 2023-12-18 at 07 01 30

I will close as this is going off topic

**Comment by eddiejaoude** [comment]
#9406

**Pull request closed without merging**
