### PR TITLE
improve the overall visual hierarchy of the features section  #8810

### LINKED ISSUE #8810: [Improve] Making the visual hierarchy of the features section better.
### Description

Here in the following image you can see that in the **features section** of the website, h3 has a `font-weight` of 500 

2023-08-27 13_06_50-BioDrop - connect to your audience with a single link - Brave

Which can be improved and made `700` to improve the overall visual hierarchy of the features section.

Here is the improved version with `font-weight: 700;`

2023-08-27 13_07_26-BioDrop - connect to your audience with a single link - Brave

## Why?

Because this improves the overall visual hierarchy and thus puts more emphasis on the features.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by theunhackable**
## Fixes Issue

Closes #8810

## Changes proposed

Requested to change the contrast between Heading text and paragraph text

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Now the contrast looks like this in Light Mode 👇:

Screenshot from 2023-08-29 14-45-20
Screenshot from 2023-08-29 14-45-30

In dark mode 👇:
Screenshot from 2023-08-29 14-56-00
Screenshot from 2023-08-29 14-56-07

## Note to reviewers

Made the paragarph text `70%` of the `text-primary-low` to develop contrast between heading which is at `100%` of `text-primary-low`
I have gone through testimonial section where I found an ambigious padding( given twice ) which  I removed. It won't effect anything.

### CODE REVIEW

**Comment by Dun-sin** [comment]
@theunhackable can you edit your PR title to be more descriptive of what you did?
you can look at how other pull requests did it -> https://github.com/EddieHubCommunity/BioDrop/pulls

**Comment by theunhackable** [comment]
> @theunhackable can you edit your PR title to be more descriptive of what you did?
> 
> you can look at how other pull requests did it -> https://github.com/EddieHubCommunity/BioDrop/pulls

How to edit it?

**Comment by Dun-sin** [comment]
> > @theunhackable can you edit your PR title to be more descriptive of what you did?
> > you can look at how other pull requests did it -> https://github.com/EddieHubCommunity/BioDrop/pulls
> 
> How to edit it?

You should see something like this close to the title, click on "Edit"
image

**Comment by theunhackable** [comment]
yead

> > > @theunhackable can you edit your PR title to be more descriptive of what you did?
> > > you can look at how other pull requests did it -> https://github.com/EddieHubCommunity/BioDrop/pulls
> > 
> > 
> > How to edit it?
> 
> You should see something like this close to the title, click on "Edit" image

yeah I did it thanks ❤️. Is it good now?

**Comment by Dun-sin** [comment]
> 
> > > > @theunhackable can you edit your PR title to be more descriptive of what you did?
> > > > you can look at how other pull requests did it -> https://github.com/EddieHubCommunity/BioDrop/pulls
> > > 
> > > 
> > > How to edit it?
> > 
> > You should see something like this close to the title, click on "Edit" image
> 
> yeah I did it thanks ❤️. Is it good now?

It's alright, good job👌🏽

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
