### PR TITLE
Maxton4life patch 1 1

### PR DESCRIPTION
**Pull request by maxton4life**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by maxton4life** [comment]
How do I delete this branch?

**Comment by kumarsonsoff3** [comment]
Not sure why you want to delete this branch!? You can directly add the changes to this branch to be included in this PR. 

--
**To delete this branch:** Just close the PR, and then you'll have the delete branch option down there, else delete from [here](https://github.com/maxton4life/BioDrop/branches).

**Comment by sital002** [comment]
Since you have  already created a new Pull Request https://github.com/EddieHubCommunity/BioDrop/pull/9369 you can close this Pull Request

**Comment by SaraJaoude** [comment]
> Since you have already created a new Pull Request #9369 you can close this Pull Request

Given the new Pull Request, which we will assume reflects the latest changes you want, I am closing this one.

**Pull request closed without merging**
