### PR TITLE
Fixed the Issue #10203 - The icon drop-down suggestions are not visible properly

### LINKED ISSUE #10203: [BUG] Icon drop-down suggestions are not visible properly
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

 v2.99.11

### Description

Icon drop-down suggestions are not visible properly in Edit section of Milestone. If we type 'FaLink' it suggests an icon related to Link, but due to the transparent background, suggestions are not visible properly. I added a screenshot for reference.

Icon drop-down 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to [Milestone](https://www.biodrop.io/account/manage/milestones) page.
2. Click on the pencil Icon for Edit Milestone
3. Type 'FaLink' in Icon section, Icon Drop Down suggestions are not visible properly

### Screenshots

Another Screenshot for Reference:

Icon Drop down Screenshot

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will make a background color white so Icon drop-down suggestions will visible properly.

### PR DESCRIPTION
**Pull request by chetannada**
Closes #10203

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Normal Mode:

Dark Mode:

## Note to reviewers

I have added a screenshot, and it's working fine in both normal and dark mode.

### CODE REVIEW

**Comment by luismr00** [comment]
Reviewed the changes and it works well. Although, the options do not overlap on top of the elements below such as the save button anymore. Instead it pushes the elements below once it shows all the searched options. In my opinion it looks better.
Screenshot 2024-02-15 at 1 09 35 PM (2)
Screenshot 2024-02-15 at 1 09 47 PM (2)

**Review by luismr00 — COMMENTED** [review]
This is the only line that needed to be adjusted to fix the problem. Although, the options do not overlap on top of the elements below such as the save button anymore. Instead it pushes the elements below once it shows all the searched options. In my opinion it looks better but will leave it up to the maintainers to agree and approve. 
Screenshot 2024-02-15 at 1 09 35 PM (2)
Screenshot 2024-02-15 at 1 09 47 PM (2)

**Review by luismr00 — APPROVED** [review]
Verified the new changes and works well 👍

**Comment by chetannada** [comment]
> Verified the new changes and works well 👍

Thanks 👍

**Comment by chetannada** [comment]
Hi @SaraJaoude @eddiejaoude 
Any update on this PR? because it's 3 weeks old!

**Review by kumarsonsoff3 — APPROVED** [review]
Looks good, Chetan! Thanks for Contributing! 🎉

**Review by matrix-compute — APPROVED** [review]

**Pull request merged**
