### PR TITLE
Fix: Make links page responsive on mobile view

### LINKED ISSUE #9907: [BUG] links page in not responsive on mobile view
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Local Development

### Version of BioDrop (for example "v1.2.3")

2.96.0

### Description

While testing the project locally I noticed that the ```account/links``` page is not responsive.

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to http://localhost:3000/account/manage/links page in mobile view.

### Screenshots

image

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_No response_

### PR DESCRIPTION
**Pull request by sohail-313**
## Fixes Issue

Closes #9907

## Changes proposed

- Implemented responsive design for the links page on mobile view.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Video Recording

https://github.com/EddieHubCommunity/BioDrop/assets/85786620/4963c748-e260-482e-922f-a2c867d2eb02

## Note to reviewers

No specific notes for reviewers at the moment. The changes are straightforward and align with the outlined bugfix for the responsive issue. If you have any questions or suggestions, please feel free to let me know.

### CODE REVIEW

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
Hello! This looks good on the account page, but unfortunately is affecting the public facing profile.  On that page the link text should remain left aligned (versus centered).

Please adjust so these changes only affect the account management view.

**Comment by sohail-313** [comment]
> Hello! This looks good on the account page, but unfortunately is affecting the public facing profile. On that page the link text should remain left aligned (versus centered).
> 
> Please adjust so these changes only affect the account management view.

Can you please share screenshot

**Comment by eddiejaoude** [comment]
The other places links component is used does not look right. I think it might be better to hide the extra info (badges) on smaller screens and truncate the text

Screenshot 2024-01-15 at 09 26 31

**Comment by sohail-313** [comment]
> The other places links component is used does not look right. I think it might be better to hide the extra info (badges) on smaller screens and truncate the text
> 
> Screenshot 2024-01-15 at 09 26 31

Yes, it can be done. However, what if the user wants to edit those links?

**Comment by eddiejaoude** [comment]
> what if the user wants to edit those links?

don't hide the edit button, just the extra info, which they can then see and edit when they edit the link

**Comment by eddiejaoude** [comment]
Closing PR as the author is not responding

**Pull request closed without merging**
