### PR TITLE
feat: archiving project redirect to github profile

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

Redirect all profile requests to their GitHub profile

For example `BioDrop.io/eddiejaoude` -> `GitHub.com/eddiejaoude`

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by amandamartin-dev — COMMENTED** [review]
@eddiejaoude I ran this in code spaces and it redirects to main github for me meaning my github feed (presumably only if I"m already logged in). Is this the correct experience? Want to make sure I"m understanding the intention correctly here before approval

**Comment by eddiejaoude** [comment]
Hi @amandamartin-dev , sorry for my slow reply and thank you for testing! Every URI will redirect because we don't know if it is a username or an actual page like homepage or docs. 

I guess you visited the homepage of BioDrop? Which redirected you to the homepage of GitHub.

We are not announcing that BioDrop will redirect as we prefer people to stop using their BioDrop URL, but we still see people using it so I was keen to not have a broken link for people and redirect to their GitHub profile (if their personal BioDrop page was visited - I was not worrying about pages like the homepage or the docs page etc)

**Comment by amandamartin-dev** [comment]
> Hi @amandamartin-dev , sorry for my slow reply and thank you for testing! Every URI will redirect because we don't know if it is a username or an actual page like homepage or docs.
> 
> I guess you visited the homepage of BioDrop? Which redirected you to the homepage of GitHub.
> 
> We are not announcing that BioDrop will redirect as we prefer people to stop using their BioDrop URL, but we still see people using it so I was keen to not have a broken link for people and redirect to their GitHub profile (if their personal BioDrop page was visited - I was not worrying about pages like the homepage or the docs page etc)

Ah okay - so the main page definitely redirects.  I will check some other pages an profiles as well to confirm thre as well. Thanks!

**Review by amandamartin-dev — CHANGES_REQUESTED** [review]
@eddiejaoude following up on your clarification I think this PR is doing more than you want it to.

It does redirect profile pages to github profiles pages as expected, however, it also appends github to ALL biodrop subdirectories as well so for example...

biodrop.com/repos redirects here
page-redirect-repos

and /events redirects here
events

**Comment by eddiejaoude** [comment]
Thanks @amandamartin-dev for testing again. Yes it will do all paths to GitHub paths - I know it does more than we need, but not sure how to only include profiles as we won't have the DB anymore and I just want to have a very simple redirect app 

I am open to any suggestions on how to make this better, but as there will be no website for people to navigate to `/docs` etc, I think the only links used will be profile links that have not been updated yet to another platform - so I think it is ok?

**Comment by amandamartin-dev** [comment]
> Thanks @amandamartin-dev for testing again. Yes it will do all paths to GitHub paths - I know it does more than we need, but not sure how to only include profiles as we won't have the DB anymore and I just want to have a very simple redirect app
> 
> I am open to any suggestions on how to make this better, but as there will be no website for people to navigate to `/docs` etc, I think the only links used will be profile links that have not been updated yet to another platform - so I think it is ok?

Ah I see - without a database you could "whitelist" full URLs that redirect to a single page for biodrop explaining that the project has been sunset but encouraging folks to come explore other EddieHub Repos and join the community to stay up to date on whats next? wdyt?

**Review by amandamartin-dev — DISMISSED** [review]
changed to approved since this behavior is expected and correct

**Comment by eddiejaoude** [comment]
> Ah I see - without a database you could "whitelist" full URLs that redirect to a single page for biodrop explaining that the project has been sunset but encouraging folks to come explore other EddieHub Repos and join the community to stay up to date on whats next? wdyt?

I like the idea 👍  At least we could do it for the homepage. Thanks @amandamartin-dev

**Comment by eddiejaoude** [comment]
I also removed the header and the footer, to hopefully reduce confusion

**Pull request merged**
