### PR TITLE
fix: Old screenshots on home page are replaced by new once

### LINKED ISSUE #9831: [BUG] Incorrect UI screenshot on home page
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.90.1

### Description

After recent changes were made to the project, there is a noticeable discrepancy between the UI screenshot displayed on the home page (search by tags section) and the actual search page UI. The home page (search by tags section) appears to be showing an outdated or incorrect screenshot.

### Steps to Reproduce

1. go to https://www.biodrop.io/
2. compare the UI screenshot displayed on the home page (search by tags section) with the actual search page UI.

### Screenshots

**Home page (search by tags section) with incorrect UI screenshot**
homepage-incorrect

**Actual search page screenshot**
search-page-actual

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

_Edited by @kumarsonsoff3_

You need to edit the below screenshot src with the updated one: 
https://github.com/EddieHubCommunity/BioDrop/blob/f85ead6b9cbf97aa871d22dc3fdab71de92eb90a/pages/index.js#L88

### PR DESCRIPTION
**Pull request by omkar342**
## Fixes Issue

Closes #9831 

## Changes proposed
The task was to replace old screenshots on the home page with new ones.
Refer screenshots sections to know more.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

Old Screenshots

1.
old_search_tags_sc

2.
eddie_previous_sc

3.
previous_sc_0

New Screenshots

1.
new_search_tag_sc

2.
eddie_new_sc_2

3.
previous_sc

### CODE REVIEW

**Comment by badrivlog** [comment]
looks great 👏

before:
before
after:
after

**Comment by omkar342** [comment]
Thanks @badrivlog 👍

**Comment by eddiejaoude** [comment]
Great collaboration 💪  we will take a look soon

**Review by kumarsonsoff3 — DISMISSED** [review]
Looks good, Thanks for Contributing! 🎉

**Pull request merged**
