### PR TITLE
style: fix light theme border issue

### LINKED ISSUE #9608: [FEATURE] Vertical lines color black in light mode
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

It's an enhancement

### Proposed Solution

In light mode the vertical lines are not visible, I want to fix this by making the colour of the vertical lines black.

Kindly assign me this issue.

### Screenshots

image
image

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

~~I'll change the color on light mode by changing the CSS~~

Edit:
In light mode use the colour of the font.  Changes can be made in the Tailwind classes `pages/index.js`

### PR DESCRIPTION
**Pull request by singodiyashubham87**
## Fixes Issue

Fixes #9608 

## Changes proposed

Change border color on light theme

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

image

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution. I think it would be less duplication if the divide classes were moved to the parent `div` where the other divide classes are used `divide-x-0 sm:divide-x`

**Comment by singodiyashubham87** [comment]
@eddiejaoude I have also thought of this but it won't work this way, I tried applying the "divide-black" class on the parent div but it does not change the child's border color and that's why I have to apply it to the child div.

**Comment by eddiejaoude** [comment]
> eddiejaoude I have also thought of this but it won't work this way, I tried applying the "divide-black" class on the parent div but it does not change the child's border color and that's why I have to apply it to the child div.

I just tested it and it worked fine for me

```js
<div className="flex flex-col sm:flex-row gap-4 sm:gap-0 justify-center items-center divide-x-0 sm:divide-x divide-dark-2 dark:divide-primary-low">
```

**Comment by singodiyashubham87** [comment]
@eddiejaoude I'm so sorry for the confusion from my side, I have updated the code now; Please validate and merge the PR.

**Review by eddiejaoude — APPROVED** [review]
Thank you

**Pull request merged**
