### PR TITLE
Create mdwasim74.json

### PR DESCRIPTION
**Pull request by mdwasim74**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8767"></a>

### CODE REVIEW

**Review by bharat5604 — APPROVED** [review]
Seems Good

**Comment by sital002** [comment]
> Seems Good

The file should be in json. Please rename the file from ```data/mdwasim74.jason``` to ``` data/mdwasim74.json```.

**Review by SaraJaoude — CHANGES_REQUESTED** [review]
It should be `.json` (and not jason). 

Please change the file name from data/mdwasim74.jason to `data/mdwasim74.json`

**Review by mdwasim74 — COMMENTED** [review]
please review..

**Review by sital002 — APPROVED** [review]
Looks good 👍
Welcome to Eddie Hub Community 🎉🎉

**Review by SaraJaoude — APPROVED** [review]

**Pull request merged**
